# Xcode
- task: Xcode@5
  inputs:
    actions: 'build'
    packageApp: true
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

Encountered error(s) while parsing pipeline YAML:
/azure-pipelines.yml (Line: 2, Col: 1): A sequence was not expected
/azure-pipelines.yml: (Line: 12, Col: 1, Idx: 376) - (Line: 12, Col: 1, Idx: 376): While parsing a block collection, did not find expected '-' indicator.